version: '3'

services: 
  app:
    image: piyushagni5/nodeblogapp:1.0
    ports:
      - "3000:3000"
    volumes:
      - myremotevolume:/usr/src/app
      
    restart: always
    links: 
      - mongo

  mongo:
    image: mongo
    ports: 
      - "27017:27017"

volumes: 
  myremotevolume:


